"""Report generator (PRD §11.6.2): templates → validated facts → DOCX with citations, missing-fact flags and a conflicts section.

Only facts with validation_status in (valid, verified, conflict) are used; conflicts are surfaced, never silently resolved.
"""
from __future__ import annotations

import datetime as dt
import re
from collections import defaultdict

from docx import Document as Docx
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

from . import store
from .db import Conflict, Document, Entity, Fact, Report, next_code
from .docai.normalize import to_display

TEMPLATES = {
    "production_summary": {
        "title": "Coal Production & Despatch Summary",
        "description": "Company-wise production (and despatch) for a fiscal year or month, totals validated, with citations.",
        "params": ["period", "entities (optional)"],
        "sections": [("Production", "production"), ("Despatch / Offtake", "dispatch"), ("Overburden Removal", "overburden")],
    },
    "parliament_brief": {
        "title": "Parliamentary Question Brief",
        "description": "Answer to a question with every number cited to page/table, plus caveats for conflicts.",
        "params": ["question"],
        "sections": [],
    },
    "resource_inventory": {
        "title": "Geological Resource Inventory Summary",
        "description": "State-wise / category-wise coal & lignite resources as on a date (CMPDI/GSI inventory).",
        "params": ["period (as on date) optional"],
        "sections": [("Coal resources (measured)", "resources_measured"), ("Coal resources (indicated)", "resources_indicated"),
                     ("Coal resources (inferred)", "resources_inferred"), ("Coal resources (total)", "resources_total"),
                     ("Lignite resources (total)", "lignite_resources_total")],
    },
    "conflict_register": {
        "title": "Cross-Document Conflict Register",
        "description": "All open conflicts with the competing values, their sources and the system's explanation.",
        "params": [],
        "sections": [],
    },
    "mine_performance": {
        "title": "Mine-wise Production Performance",
        "description": "Mine-level production / overburden vs target with achievement, from monthly statistics.",
        "params": ["period", "subsidiary (optional)"],
        "sections": [("Mine production", "production"), ("Mine overburden", "overburden")],
    },
}


def _facts(session, predicate: str, period: str | None, entity_ids: list[str] | None, subject_types: list[str] | None = None,
           qualifier=("actual", "provisional"), with_dimension: bool = False) -> list[Fact]:
    q = session.query(Fact).filter(Fact.predicate == predicate, Fact.validation_status.in_(["valid", "verified", "conflict"]), Fact.qualifier.in_(list(qualifier)))
    if period:
        q = q.filter(Fact.period == period)
    if entity_ids:
        q = q.filter(Fact.subject_entity_id.in_(entity_ids))
    q = q.filter(Fact.dimension_text.isnot(None)) if with_dimension else q.filter(Fact.dimension_text.is_(None))
    facts = [f for f in q.all() if not (f.confidence or {}).get("_partial_total")]
    if subject_types:
        ents = {e.entity_id: e for e in session.query(Entity).filter(Entity.entity_id.in_({f.subject_entity_id for f in facts})).all()}
        facts = [f for f in facts if ents.get(f.subject_entity_id) and ents[f.subject_entity_id].entity_type in subject_types]
    return facts


def _cite(doc: Document, f: Fact) -> str:
    loc = f"p{f.page_number}"
    if f.table_id:
        loc += ", table"
    return f"{doc.code} {loc}"


def generate(session, template_id: str, params: dict, user=None) -> Report:
    if template_id not in TEMPLATES:
        raise ValueError(f"unknown template {template_id}")
    tpl = TEMPLATES[template_id]
    period = params.get("period")
    entity_ids = params.get("entity_ids") or None
    docx = Docx()
    st = docx.styles["Normal"]; st.font.name = "Calibri"; st.font.size = Pt(10.5)
    title = params.get("title") or f"{tpl['title']}" + (f" — {period}" if period else "")
    h = docx.add_heading(title, 0)
    meta = docx.add_paragraph()
    meta.add_run(f"Generated by EvidenceOS on {dt.datetime.utcnow():%d %b %Y %H:%M} UTC · Template: {template_id} · ").italic = True
    meta.add_run("Every figure below is traceable to a source page/table (see Sources). Values marked ⚠ have conflicting sources.").italic = True

    docs = {d.document_id: d for d in session.query(Document).all()}
    ents = {e.entity_id: e for e in session.query(Entity).all()}
    used: list[str] = []
    missing: list[str] = []
    conflict_codes: set[str] = set()
    cited_docs: dict[str, set] = defaultdict(set)

    def add_fact_table(facts: list[Fact], label_col="Entity", key=None, name_of=None):
        groups: dict[str, list[Fact]] = defaultdict(list)
        for f in facts:
            groups[key(f) if key else (f.subject_entity_id or f.subject_text)].append(f)
        table = docx.add_table(rows=1, cols=4); table.style = "Light Grid Accent 1"
        hdr = table.rows[0].cells
        hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = label_col, "Value", "Source", "Confidence"
        order = sorted(groups.items(), key=lambda kv: (ents.get(kv[0]).is_aggregate if ents.get(kv[0]) else False, ents.get(kv[0]).canonical_name if ents.get(kv[0]) else kv[0]))
        for sid, fl in order:
            e = ents.get(sid)
            name = name_of(fl[0]) if name_of else (e.canonical_name if e else fl[0].subject_text)
            vals = defaultdict(list)
            for f in fl:
                vals[to_display(f.value, f.unit)].append(f)
            row = table.add_row().cells
            row[0].text = name
            if len(vals) == 1:
                v, ff = next(iter(vals.items()))
                row[1].text = v
                row[2].text = "; ".join(sorted({_cite(docs[f.document_id], f) for f in ff}))
                row[3].text = f"{max(f.overall_confidence or 0 for f in ff):.0%}"
            else:
                row[1].text = "⚠ " + " / ".join(vals.keys())
                row[2].text = "; ".join(f"{v}: " + ", ".join(sorted({_cite(docs[f.document_id], f) + ' (' + f.qualifier + ')' for f in ff})) for v, ff in vals.items())
                row[3].text = "conflict"
                for f in fl:
                    for c in session.query(Conflict).filter(Conflict.status == "open", Conflict.subject_entity_id == f.subject_entity_id, Conflict.period == f.period).all():
                        conflict_codes.add(c.code)
            for f in fl:
                used.append(f.fact_id); cited_docs[f.document_id].add(f.page_number)

    if template_id in ("production_summary", "resource_inventory", "mine_performance"):
        subject_types = ["mine"] if template_id == "mine_performance" else (["state", "country", "coal_type", "coalfield_group", "depth_range"] if template_id == "resource_inventory" else ["company", "subsidiary", "country", "sector"])
        for sec_title, pred in tpl["sections"]:
            facts = _facts(session, pred, period, entity_ids, subject_types)
            if template_id == "mine_performance" and params.get("subsidiary_id"):
                facts = [f for f in facts if ents.get(f.subject_entity_id) and ents[f.subject_entity_id].parent_entity_id == params["subsidiary_id"]]
            docx.add_heading(sec_title, 1)
            if not facts:
                p = docx.add_paragraph(); r = p.add_run(f"⚠ No validated {pred.replace('_', ' ')} facts found for {period or 'the requested scope'} — section left intentionally incomplete.")
                r.font.color.rgb = RGBColor(0xB0, 0x30, 0x30)
                missing.append(f"{sec_title} ({pred}) for {period or 'any period'}")
                continue
            add_fact_table(facts)
            if pred == "dispatch":
                # sector-wise despatch (dimension = consuming sector) for the same scope
                sfacts = _facts(session, pred, period, entity_ids, subject_types, with_dimension=True)
                if sfacts:
                    docx.add_paragraph("Sector-wise despatch:").runs[0].italic = True
                    add_fact_table(sfacts, label_col="Producer → Sector", key=lambda f: f"{f.subject_entity_id}|{f.dimension_text}",
                                   name_of=lambda f: f"{ents[f.subject_entity_id].canonical_name if ents.get(f.subject_entity_id) else f.subject_text} → {f.dimension_text}")
            # targets alongside (if any)
            tfacts = _facts(session, pred, period, entity_ids, subject_types, qualifier=("target",))
            if tfacts:
                docx.add_paragraph(f"Targets ({len(tfacts)} entries) are available for this section:").runs[0].italic = True
                add_fact_table(tfacts)
    elif template_id == "parliament_brief":
        from .retrieval import qa
        question = params.get("question") or "What was the all-India coal production in the latest fiscal year?"
        res = qa.answer(session, question, user=user)
        docx.add_heading("Question", 1); docx.add_paragraph(question)
        docx.add_heading("Answer", 1)
        for line in (res.get("answer") or "").split("\n"):
            docx.add_paragraph(re.sub(r"\*\*", "", line))
        docx.add_paragraph(f"Route: {res.get('route')} · Confidence: {res.get('confidence', 0):.0%}").runs[0].italic = True
        if res.get("missing_evidence"):
            missing.append("Question could not be answered from validated evidence")
        docx.add_heading("Citations", 1)
        for c in res.get("citations", []):
            docx.add_paragraph(f"{c.get('document_code')} — {c.get('document_title')}, page {c.get('page')}" + (f" · {c.get('value')}" if c.get('value') else "") + (f" · {c.get('snippet')[:160]}" if c.get('snippet') else ""), style="List Bullet")
            if c.get("fact_id"):
                used.append(c["fact_id"])
            if c.get("document_id"):
                cited_docs[c["document_id"]].add(c.get("page"))
        for c in res.get("conflicts", []):
            conflict_codes.add(c["code"])
    elif template_id == "conflict_register":
        cfs = session.query(Conflict).filter(Conflict.status == "open").order_by(Conflict.severity.desc()).all()
        docx.add_heading(f"Open conflicts: {len(cfs)}", 1)
        table = docx.add_table(rows=1, cols=5); table.style = "Light Grid Accent 1"
        for i, t in enumerate(["Code", "Subject / metric / period", "Values (source, page, status)", "Severity", "Explanation"]):
            table.rows[0].cells[i].text = t
        for c in cfs:
            row = table.add_row().cells
            row[0].text = c.code; row[1].text = f"{c.subject_text} · {c.predicate} · {c.period}"
            row[2].text = "\n".join(f"{v['value']} — {v['document_code']} p{v['page']} ({v.get('qualifier')})" for v in c.values)
            row[3].text = c.severity; row[4].text = c.explanation or ""
            conflict_codes.add(c.code)
            for fid in c.fact_ids or []:
                used.append(fid)
                f = session.get(Fact, fid)
                if f:
                    cited_docs[f.document_id].add(f.page_number)

    if conflict_codes and template_id != "conflict_register":
        docx.add_heading("Conflicts flagged in this report", 1)
        for code in sorted(conflict_codes):
            c = session.query(Conflict).filter(Conflict.code == code).first()
            if c:
                docx.add_paragraph(f"{c.code} [{c.severity}] {c.subject_text} — {c.predicate} {c.period}: " + "; ".join(f"{v['value']} ({v['document_code']} p{v['page']}, {v.get('qualifier')})" for v in c.values) + f". {c.explanation}", style="List Bullet")
    if missing:
        docx.add_heading("Missing facts", 1)
        for m in missing:
            docx.add_paragraph(m, style="List Bullet")
    docx.add_heading("Sources", 1)
    for did, pgs in cited_docs.items():
        d = docs.get(did)
        if d:
            docx.add_paragraph(f"{d.code} — {d.title} ({d.source or 'n/a'}; {d.document_type}); pages {', '.join(str(p) for p in sorted(p for p in pgs if p))}. SHA-256 {d.sha256[:16]}…", style="List Bullet")
    docx.add_paragraph().add_run("Provenance: original document → page → region/table cell → extracted value → normalized value → validated fact → this report. AI assisted extraction; the validated facts and their evidence are the system of record.").italic = True

    rep = Report(template_id=template_id, title=title, generated_by=getattr(user, "user_id", None), params=params, facts_used=sorted(set(used)), missing=missing,
                 status="generated")
    session.add(rep); session.flush()
    path = store.reports_dir() / f"{rep.report_id}.docx"
    docx.save(str(path))
    rep.document_path = str(path)
    store.save_report_artifact(path, rep.report_id)
    session.flush()
    return rep
